import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { 
  Shield, 
  Brain, 
  MessageCircle, 
  Trophy, 
  AlertTriangle, 
  Users,
  Zap,
  Target
} from 'lucide-react';

const Home = () => {
  const { user } = useAuth();

  const features = [
    {
      icon: AlertTriangle,
      title: 'AI-Powered Alerts',
      description: 'Get intelligent emergency alerts generated by advanced AI analysis of real-time data.',
      color: 'text-emergency-600'
    },
    {
      icon: Brain,
      title: 'Smart Quiz System',
      description: 'Test your emergency preparedness knowledge with AI-generated quizzes tailored to your level.',
      color: 'text-primary-600'
    },
    {
      icon: MessageCircle,
      title: 'AI Assistant',
      description: 'Chat with our AI assistant for personalized emergency preparedness advice and support.',
      color: 'text-success-600'
    },
    {
      icon: Trophy,
      title: 'Gamification',
      description: 'Earn points, maintain streaks, and unlock badges as you learn and improve your preparedness.',
      color: 'text-warning-600'
    }
  ];

  const stats = [
    { icon: Users, label: 'Active Users', value: '10,000+' },
    { icon: Zap, label: 'AI Responses', value: '50,000+' },
    { icon: Target, label: 'Quizzes Completed', value: '25,000+' },
    { icon: Shield, label: 'Lives Protected', value: 'Countless' }
  ];

  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6">
            Be Ready for
            <span className="text-emergency-600 block">Any Emergency</span>
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            CalamitySense uses advanced AI to help you prepare for disasters, stay informed, 
            and build the skills needed to protect yourself and your community.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            {user ? (
              <Link to="/dashboard" className="btn-primary text-lg px-8 py-3">
                Go to Dashboard
              </Link>
            ) : (
              <>
                <Link to="/register" className="btn-primary text-lg px-8 py-3">
                  Get Started Free
                </Link>
                <Link to="/login" className="btn-secondary text-lg px-8 py-3 border-2 border-primary-600 text-primary-600 hover:bg-primary-50">
                  Sign In
                </Link>
              </>
            )}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Intelligent Emergency Preparedness
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our AI-powered platform combines cutting-edge technology with proven emergency 
              preparedness strategies to keep you and your loved ones safe.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => {
              const Icon = feature.icon;
              return (
                <div 
                  key={index}
                  className="bg-white p-6 rounded-xl shadow-lg hover:shadow-xl transition-shadow duration-300 text-center group"
                >
                  <div className={`inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-50 mb-4 group-hover:scale-110 transition-transform duration-300`}>
                    <Icon className={`w-8 h-8 ${feature.color}`} />
                  </div>
                  <h3 className="text-xl font-semibold text-gray-900 mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="bg-gradient-to-r from-primary-600 to-primary-800 py-16">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-white mb-4">
              Making a Real Impact
            </h2>
            <p className="text-xl text-primary-100 max-w-2xl mx-auto">
              Join thousands of people who are already better prepared for emergencies 
              thanks to CalamitySense.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, index) => {
              const Icon = stat.icon;
              return (
                <div key={index} className="text-center">
                  <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-white/10 mb-4">
                    <Icon className="w-8 h-8 text-white" />
                  </div>
                  <div className="text-3xl font-bold text-white mb-2">
                    {stat.value}
                  </div>
                  <div className="text-primary-100">
                    {stat.label}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gray-100 py-16 rounded-2xl">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl font-bold text-gray-900 mb-6">
            Ready to Get Started?
          </h2>
          <p className="text-xl text-gray-600 mb-8">
            Join CalamitySense today and take the first step towards better emergency preparedness. 
            Your safety and peace of mind are worth it.
          </p>
          
          {!user && (
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/register" className="btn-emergency text-lg px-8 py-3">
                Sign Up Now
              </Link>
              <Link to="/alerts" className="btn-primary text-lg px-8 py-3">
                View Live Alerts
              </Link>
            </div>
          )}
        </div>
      </section>
    </div>
  );
};

export default Home;